# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
