# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_auto_20180413_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='o_num',
            field=models.CharField(max_length=128),
        ),
    ]
